name: valbury_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.0-133.0.dev <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  equatable: 2.0.3
  form_validator: 1.0.1
  get_storage: 2.0.3
  salomon_bottom_bar: 3.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
